[properties]
paper-size = "A4"
background = "#000000"
font-size = 18
color = "#FFFFFF"

[[slides]]
layout = "vertical"  # Stacks elements vertically
elements = [
    {oftype = "text", content = "Welcome to the Presentation", font_size = 40, color = "#ffffff", background_color = "#000000" },
    {oftype = "image", content = "/home/neo/Gits/spectra/src/Indian_Institute_of_Astrophysics_Logo.svg", size = { width = 400, height = 300 } },
    # {oftype = "image", content = "/home/neo/Gits/spectra/src/2024-07-24 11-03-00.gif"},
    {oftype = "points", points = ["This is the first point", "This is the second point", "This is the third point"], color = "#FFFFFF" },
]

[[slides]]
layout = "horizontal"  # Aligns elements horizontally
elements = [
    {oftype = "video", content = "/home/neo/2024-08-16 10-36-34.mp4", autoplay = true },
    {oftype = "text", content = "Enjoy the video", font_size = 30, color = "#00ff00" }
]

[[slides]]
layout = "grid"  # Arranges elements in a grid
grid = { rows = 2, columns = 2 }
elements = [
    {oftype = "text", content = "Grid Element 1", font_size = 20 },
    {oftype = "image", content = "path/to/image1.png", size = { width = 200, height = 150 } },
    {oftype = "image", content = "path/to/image2.png", size = { width = 200, height = 150 } },
    {oftype = "text", content = "Grid Element 4", font_size = 20 }
]